server:
  port: 8010

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
            enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8012/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
